### DISCUSSION TITLE
Tunable White - Preset Tuning Selection from Script/Automation?

### DISCUSSION THREAD

**Discussion by BeSpec-Dev** [sbidy/wiz_light#207] [Q&A] [answered]
I'm tackling my first HomeAssistant automation since i've started my setup this month: Tunable white lightbulbs on a time-based automation.

I've had success at toggling On/Off my two first Wiz lightbulbs with light groups and a basic automation. Woo-hoo!

Problem: I have not determined how to set tuned white color schemes in automations or scripts. _FYI, cross-posted to reddit.com/homeassistant/_

I have successfully added light switches to my lovelace interface, and when i click on the entity name, it brings up a pop-up with additional controls for brightness, color temperature, and _effect_.

The _Effect_ selection allows me to use preset color temp/ brightness settings. Very handy. Further, the pre-populated list matches the options available in the Wiz proprietary mobil app.

I would like to use the same preset options available under the effect option. I have scoured the Wiz_Light GitHub repository, looking for any mention of any of the preset names i find under the drop down. I haven't found mention of "_cozy_", "_night light"_, or any other preset. After looking through the custom_components/wiz_light/light.py file, I see reference to inherited features from base HomeAssistant light components. Perhaps these presets are found somewhere inside HomeAssistant code? I've searched there too, and can't figure it out.

Regardless of where the presets reside, I'm trying to simply turn on the light, and _tune the white color according to a preset thats already available from a dropdown list in homeassistant_.

I've tried something as simply as:

```
- id: '1234567890'
  alias: Living Room Night Light Mode
  description: Turns light into nightlight mode at 11pm
  trigger:
  - platform: time
    at: '23:00:00'
  condition: []
  action:
  - service: light.turn_on
    target:
      entity_id: light.family_room_lights
    data:
      effect: cozy
  mode: single
```
Apparently my attempt to throw a name at "effect" in the data: field isn't sufficient. It could be a simple error. Regardless, I've learned a lot so far on this first project!!

**Comment by BeSpec-Dev** [comment, marked as answer]
Answer! 

A friendly redditor assisted me by directing me to the Home Assistant _Developer - States_ tab, and recommending i look at the listed attributes of a given entity.  Per the screenshot below my long-desired "list of presets" is there for the entity.  Further, it looks like I was very close in my original code (case sensitive attributes).

Anyway, I've included a screenshot of the developer State tab, for others to take a peek at. 



<img width="637" alt="Screen Shot 2021-11-25 at 11 11 04 PM" src="https://user-images.githubusercontent.com/35648267/143525650-0b32ee89-fa54-4758-b9a9-5549b3f5c858.png">

Final functional script: 
```
living_room_lights_night_light_mode:
  sequence:
  - service: light.turn_on
    target:
      entity_id:
      - light.bulb200
      - light.bulb201
    data:
      effect: Night light
  mode: single
  alias: Living Room Lights - Night Light Mode
```
Thanks for a awesome project supporting the Wiz family!
