### DISCUSSION TITLE
Issue with rgb_color / DHCP with multiple bulbs

### DISCUSSION THREAD

**Discussion by johanjongsma** [sbidy/wiz_light#38] [Q&A]
When you change the color of a light to eg red using:
```
  - data:
      entity_id: light.office_1
      color_name: red
      brightness_pct: 100
    service: light.turn_on
```
and then change it back to white using:
```
  - service: light.turn_on
    data:
      entity_id: light.office_1
      kelvin: 4000
      brightness_pct: 100
```

the rgb_color still reports 
`(255,0,0)`
as if the light is still red, although it will be daylight.

Thank you guys for this great work; I use it in my whole house.

Johan
