### DISCUSSION TITLE
Unavailable - Help Me Please!

### DISCUSSION THREAD

**Discussion by sudoxreboot** [sbidy/wiz_light#93] [Q&A] [answered]
I may be going crazy. No matter what I try, it always returns the bulb as unavailable.
Installation via HACS. IP is static. So, no issue there. I've uninstalled, reinstalled, tried installing the master, v1 and v2, cut power to the bulb, multiple reboots throughout the entire process, which takes 45 years... I'm about to cry, nothing seems to work.
Config entry:
```
  - platform: wiz_light
    name: Wiz Test
    host: 192.168.1.26   
```
 Any help would be greatly appreciated!

**Comment by ChrisLizon** [comment, marked as answer]
Make sure that your bulb is connected to WiFi and working through the WiZ app on your phone first. 

The wiz light template must go under your light entry in your config.xml.  It's possible to have multiple other entites designated there. 

Also, be aware that YAML is super picky on indentation. It looks like your example is good, you may just be missing a header. Here's my light section from configuration.yaml. Ignore the template light, it's only relevant to show the overall structure of the Configuration.yaml. 

```
light:
  - platform: wiz_light
    name: "Office Overhead Light"
    host: 192.168.9.117
  - platform: wiz_light
    name: "Office Lamp"
    host: 192.168.8.105
  - platform: template
    lights:
      flux_virtual:
        friendly_name: "Flux Virtual Bulb"
        turn_on:
        turn_off:
        set_level:
        set_temperature:
```

Luckily @sbidy  has the GUI configuration ready to go for the pull into HA core, so that option should be available soon.

**Reply by sudoxreboot** [reply]
Thanks for the reply. Yeah, the bulb is definitely on and connected via WIZ. I added the config with the other light entities I've created as well, so I know it has the header. I've been controlling them with Smartthings as the middleman between the two, but it does something weird to any scene with them, the color temp is made a neat gray, but not the color it was when I saved the scene.
If I remove the add on it removes the entity, so I know it is doing SOMETHING, just won't show as anything other than unavailable.
I'm excited about the core release, but I worry that it won't work for me if this isn't. I have 13 of their bulbs and really don't want to replace them lol.
Do we have an eta on the release? Or is it possible to help test and share my experience, not out of impatience,  but more out of worry that others may have the same experience? I don't know much about coding, but I'm good at trying instructions and returning feedback.

**Reply by ChrisLizon** [reply]
Have you already configured al 13 bulbs? Are all of them having issues or just your first sample?

Simplest thing first: make sure you can ping the bulb, ideally testing from the HA machine. (I run Home Assistant core so it's easy for me, I don't know if it's easy from Home Assistant supervised. )

Have you had a chance to try a getSystemConfig from the linux command line? That will at least help you determine if everything is communicating well.

```echo '{"method":"getSystemConfig","params":{}}' | nc -u -w 1 <YOU BULB IP> 38899```

Also, you can try turning on logging for wiz_light. You would have to add a logging entry to your configuration.yaml. 

```
logger:
    default: critical
    logs:
        # log level for a custom component
        custom_components.wiz_light: debug
```
