### ISSUE TITLE
Light shows as unavailable

### ISSUE THREAD

**Issue by setegonz** [sbidy/wiz_light#16]
I followed the installation instructions. Everything ran smoothly. Although I can see the bulb created, I get the following message:

`This entity does not have a unique ID, therefore its settings cannot be managed from the UI.`
I'm running Home Assistant 0.108.6 in macOS Catalina via docker.

**Comment by sbidy** [comment]
Do you configure the bulbs with the YAML file or directly in the UI? The UI configuration is currently not working.
Can you post the part of your `lights` section from the config?

**Comment by setegonz** [comment]
I set it up manually in the yaml.

```
light:
  - platform: wiz_light
    name: <wiz_8d76bb>
    host: <192.168.108.208>
```

**Comment by VerityNH** [comment]
You should remove <> symbols out of your config
It should look like

```
light:
  - platform: wiz_light
    name: wiz_8d76bb
    host: 192.168.108.208
```

P.S. You can also use user friendly naming for your bulb for you convenience, something like

```
light:
  - platform: wiz_light
    name: Reading lamp
    host: 192.168.108.208
```
