### ISSUE TITLE
Multiple lights?

### ISSUE THREAD

**Issue by amadib** [sbidy/wiz_light#5]
The `README` isn't clear as to how to add more than one light to the `configuration.yaml` file. I have two lights and have given both a static ip address and named them through the wiz app but am unable to see them both within home assistant.

**Comment by VerityNH** [comment]
```
light:
  - platform: wiz_light
    name: <Name of the device>
    host: <IP of the bulb>
  - platform: wiz_light
    name: <Name of the device 2>
    host: <IP of the bulb 2>
  - platform: wiz_light
    name: <Name of the device N>
    host: <IP of the bulb N>
```
