### ISSUE TITLE
[Bulb Test Report] 

### ISSUE THREAD

**Issue by jarpatus** [sbidy/wiz_light#67]
**Please don't post bugs or issues here** This template is only for report a new bulb type for integration or successful test.

Provide the following information:

**1. Made an UDP request with `nc` to the bulb:**
`echo '{"method":"getSystemConfig","params":{}}' | nc -u -w 1 <YOU BULB IP> 38899`
Report the output here:

{"method":"getSystemConfig","env":"pro","result":{"mac":"a8bb5073437e","homeId":2164648,"roomId":3310124,"moduleName":"ESP03_SHTW1W_01","fwVersion":"1.21.0","groupId":0,"drvConf":[20,2],"ewf":[255,0,255,255,0,0,40],"ewfHex":"ff00ffff000028","ping":0}}

**2. Provide the native features of the bulb:**
  - Dimmer (yes/no): yes
  - Color Temp (yes/no): yes
  - Effects (yes/no): no
  - RGB (yes/no): no

**3. Tested?**
    yes/no
    If you found bug or problems with the bulb please open an new issue and add a reference to this one.

yes

**OPTIONAL**

**4. Prepare the YAML - replace `<Name>` with the ESP_XXXXXXXX name from step 1.**
  ```
    ESP03_SHTW1W_01:
       name: ESP03_SHTW1W_01
       features:
         brightness: true
         color: false
         effect: true
         color_tmp: true
       kelvin_range:
         min: 2700
         max: 6500
   ```

**Additional Info**
Add any other useful information about the bulb? Purchase link? Other stuff you want to share?

https://www.wizconnected.com/en/consumer/products/8718699786175/

**Thank you for your support**

We will integrate the bulb as soon as possible.
