### ISSUE TITLE
Bulb Implementation Report

### ISSUE THREAD

**Issue by dme** [sbidy/wiz_light#79]
**Please don't post bugs or issues here** This template is only for report a new bulb type for integration or successful test.

Provide the following information:

**1. Made an UDP request with `nc` to the bulb:**
`echo '{"method":"getSystemConfig","params":{}}' | nc -u -w 1 <YOU BULB IP> 38899`
Report the output here:

```
{
  "method": "getSystemConfig",
  "env": "pro",
  "result": {
    "mac": "a8bb50f5f453",
    "homeId": 2353415,
    "roomId": 3548790,
    "moduleName": "ESP03_SHDW1_01",
    "fwVersion": "1.21.0",
    "groupId": 0,
    "drvConf": [
      20,
      1
    ],
    "ewf": [
      255,
      0,
      255,
      255,
      0,
      0,
      0
    ],
    "ewfHex": "ff00ffff000000",
    "ping": 0
  }
}
```

**2. Provide the native features of the bulb:**
  - Dimmer (yes/no): yes
  - Color Temp (yes/no): no
  - Effects (yes/no): no
  - RGB (yes/no): no

**3. Tested?**
    yes/no
    If you found bug or problems with the bulb please open an new issue and add a reference to this one.

yes

**OPTIONAL**

**4. Prepare the YAML - replace `<Name>` with the ESP_XXXXXXXX name from step 1.**
  ```
ESP03_SHDW1_01:                                                                                                                                                               
  name: ESP03_SHDW_01                                                                                                                                                         
  features:                                                                                                                                                                   
    brightness: true                                                                                                                                                          
    color: false                                                                                                                                                              
    effect: false                                                                                                                                                             
    color_tmp: false                                                                                                                                                          
  kelvin_range:                                                                                                                                                               
    min: 2200                                                                                                                                                                 
    max: 6500                                                                                                                                                                 
   ```

**Additional Info**
Add any other useful information about the bulb? Purchase link? Other stuff you want to share?

Bought from B&Q in the UK for 10UKP on the basis that it was worth a try. Seems to work fine with this wonderful addition to HomeAssistant.

**Thank you for your support**

We will integrate the bulb as soon as possible.
