### ISSUE TITLE
Bug when setting white temperature

### ISSUE THREAD

**Issue by jappyjan** [sbidy/wiz_light#80]
The Integration works very well so far.
Except for one thing which is setting the white temperature.
Whenever i drag on the slider, it does not move even though it shows a (very high) number that changes the more i drag...
Oh and the color temperature of my bulb also does not change...

https://user-images.githubusercontent.com/10154260/104172231-39210600-5404-11eb-8a6f-8637420126dd.mov

**Comment by sbidy** [comment]
Can you please set the intrgration the "debug mode".
Add to your `configuration.yaml` this lines:
```
logger:
    default: warning
    logs:
      homeassistant.components.wiz_light: debug
```

Please forward the log output. I think there are some issues with the bulb definition.
Also update the integration to the latest release (0.2).

**Comment by jappyjan** [comment]
i updated the integration to 0.2 and did set the config options.
where is the log located?
if i look into the "home-assistant.log" file i dont see any wiz light logs... only warnings about using custom integrations....

**Comment by rkeet** [comment]
Ran into this bug as well using the RGB bulbs. Found in the `scenes.yaml` that the Duo bulbs have: 

```yaml
      supported_color_modes:
      - color_temp
      color_mode: color_temp
```

As opposed to the RGB bulbs with: 

```yaml
      supported_color_modes:
      - color_temp
      - hs
      color_mode: hs
```

When setting the color of a light using the Temperature option, the `color_mode` setting does not get changed to `color_temp` but remains `hs`.
