### ISSUE TITLE
Bulb Implementation Report

### ISSUE THREAD

**Issue by charlietomo** [sbidy/wiz_light#84]
**1. Made an UDP request with `nc` to the bulb:**
`echo '{"method":"getSystemConfig","params":{}}' | nc -u -w 1 <YOU BULB IP> 38899`
Report the output here:
```
{"method":"getSystemConfig","env":"pro","result":
{
"mac":"[snip]",
"homeId":[snip],
"roomId":[snip],
"moduleName":"ESP03_SHRGB_31",
"fwVersion":"1.21.0",
"groupId":0,
"drvConf":[25,1],
"ewf":[255,0,255,226,0,0,0],
"ewfHex":"ff00ffe2000000",
"ping":0
}}%
```
**2. Provide the native features of the bulb:**
  - Dimmer (yes/no): yes
  - Color Temp (yes/no): yes
  - Effects (yes/no): yes
  - RGB (yes/no): yes

**3. Tested?**
    yes
    If you found bug or problems with the bulb please open an new issue and add a reference to this one.

**4. Prepare the YAML - replace `<Name>` with the ESP_XXXXXXXX name from step 1.**
  ```
    ESP03_SHRGB_31:
       name: ESP03_SHRGB_31
       features:
         brightness: true
         color: true
         effect: true
         color_tmp: true
       kelvin_range:
         min: 3000
         max: 5709
   ```

**Additional Info**
Sold as `atom AT4010/WH/WIZ/TR`. 90mm Cutout.

**Thank you for your support**

We will integrate the bulb as soon as possible.

**Comment by ChrisLizon** [comment]
I think I found the manufacturer's page for that bulb, https://www.atomlighting.com.au/product/at4010/

It specifies 3000-5700k for color temperature. Can you confirm that this is the range available in the WiZ app?

**Comment by charlietomo** [comment]
That page looks like my bulb.

I wasn't sure where to find what you were asking, but had a look in the app. If I click on the colour mode, then "Custom White" I get the options in this range you outlined, `~3000K White` > `~5700K White` in 100K increments except around 4100 - 4300 which are not options (classed as `Daylight`). I also have `Warm White` which is under `~3000K White`. Is that what you meant?

Let us know if I can help with anything else.

**Comment by ChrisLizon** [comment]
That's great, that would be the "or other" part of the template. 

```
     kelvin_range:
       min: 2200 / or other?
       max: 6500 / or other?
```

```
ESP03_SHRGB_31:
     name: ESP03_SHRGB_31
     features:
       brightness: true
       color: true
       effect: true
       color_tmp: true
     kelvin_range:
       min: 2700
       max: 5700
```
